export enum PaymentMethodPropType {
    BANK_ACCOUNT_NUMBER = 'BANK_ACCOUNT_NUMBER',
    IBAN = 'IBAN',
    HOLDER_NAME = 'HOLDER_NAME',
    BANK_NAME = 'BANK_NAME',
    BIC_OR_SWIFT = 'BIC_OR_SWIFT',
    CRYPTO_WALLET_ADDRESS = 'CRYPTO_WALLET_ADDRESS',
    CARD_NUMBER = 'CARD_NUMBER'
}