export enum AuthStatus {
  NEED_TO_CONNECT_TG = 'NEED_TO_CONNECT_TG',
  NEED_TO_CONFIRM = 'NEED_TO_CONFIRM',
  CONFIRMATION_SENT = 'CONFIRMATION_SENT',
  CONFIRMED = 'CONFIRMED',
  BLOCKED = 'BLOCKED'
}
