version: '3.8'
services:
  company:
    image: ${COMPANY_IMAGE}
    ports:
      - '4202:4200'
    restart: unless-stopped
    labels:
      - 'project=company'

  freelancer:
    image: ${FREELANCER_IMAGE}
    ports:
      - '4201:4200'
    restart: unless-stopped
    labels:
      - 'project=freelancer'

  admin:
    image: ${ADMIN_IMAGE}
    ports:
      - '4203:4200'
    restart: unless-stopped
    labels:
      - 'project=admin'

  landing:
    image: ${LANDING_IMAGE}
    ports:
      - '4200:4200'
    restart: unless-stopped
    labels:
      - 'project=landing'
