export enum SessionStatusType {
  NOT_LOGGED_IN = 'NOT_LOGGED_IN',
  CONFIRMED = 'CONFIRMED',
  NEED_TO_CONNECT_TG = 'NEED_TO_CONNECT_TG',
  NEED_TO_CONFIRM = 'NEED_TO_CONFIRM',
  CONFIRMATION_SENT = 'CONFIRMATION_SENT',
  LOGGED_IN = 'LOGGED_IN',
  BLOCKED = 'BLOCKED'
}
