export enum TaskStatus {
    NEW = 'NEW',
    ASSIGNED = 'ASSIGNED',
    CANCELLED = 'CANCELLED',
    IN_PROGRESS = 'IN_PROGRESS',
    REVIEWING = 'REVIEWING',
    PAYMENT_IN_PROGRESS = 'PAYMENT_IN_PROGRESS',
    PAYMENT_ERROR = 'PAYMENT_ERROR',
    PAID = 'PAID',
}