export enum UserDataPropsType {
    FIRST_NAME = 'FIRST_NAME',
    LAST_NAME = 'LAST_NAME',
    PHONE_NUMBER = 'PHONE_NUMBER',
    BIRTH_DATE = 'BIRTH_DATE',
    DOCUMENT_NUMBER = 'DOCUMENT_NUMBER',
    TIN = 'TIN',

    //Freelancer:
    STREET = 'STREET',
    COUNTRY = 'COUNTRY',
    CITY = 'CITY',
    POSTAL_CODE = 'POSTAL_CODE',
    HOUSE_NUMBER = 'HOUSE_NUMBER'
}
