name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select deployment environment
        required: true
        options:
          - test
          - prod
          - demo
      deploy_landing:
        description: Deploy Landing
        required: false
        default: 'false'
        type: boolean
      deploy_company:
        description: Deploy Company
        required: false
        default: 'false'
        type: boolean
      deploy_freelancer:
        description: Deploy Freelancer
        required: false
        default: 'false'
        type: boolean
      deploy_admin:
        description: Deploy Admin
        required: false
        default: 'false'
        type: boolean

jobs:
  check-branch-and-env:
    runs-on: ubuntu-latest
    outputs:
      error: ${{ steps.check-branch-and-env.outputs.error }}
    steps:
      - name: Check branch and env
        id: check-branch-and-env
        run: |
          if [[ ${{ github.ref }} != 'refs/heads/main' && ${{ inputs.environment }} == 'prod' ]]; then
            echo "error=true" >> $GITHUB_ENV
            echo "### WARNING!" >> $GITHUB_STEP_SUMMARY
            echo "You are deploying to production from a branch that is not main. Please make sure you know what you are doing." >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "error=false" >> $GITHUB_ENV
          fi
      - name: Check selected projects
        id: check-selected-projects
        run: |
          if [[ ${{ github.event.inputs.deploy_landing }} == 'false' && ${{ github.event.inputs.deploy_company }} == 'false' && ${{ github.event.inputs.deploy_freelancer }} == 'false' && ${{ github.event.inputs.deploy_admin }} == 'false' ]]; then
            echo "No projects selected for deployment. Exiting."
            exit 1
          fi
      - name: Show project inputs
        run: |
          echo "### PROJECTS DEPLOY INFO" >> $GITHUB_STEP_SUMMARY
          echo "Deploy Landing: ${{ github.event.inputs.deploy_landing }}" >> $GITHUB_STEP_SUMMARY
          echo "Deploy Company: ${{ github.event.inputs.deploy_company }}" >> $GITHUB_STEP_SUMMARY
          echo "Deploy Freelancer: ${{ github.event.inputs.deploy_freelancer }}" >> $GITHUB_STEP_SUMMARY
          echo "Deploy Admin: ${{ github.event.inputs.deploy_admin }}" >> $GITHUB_STEP_SUMMARY
          echo "Environment: ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY

  build-and-push:
    needs: check-branch-and-env
    if: ${{ needs.check-branch-and-env.outputs.error != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [landing, company, freelancer, admin]
      fail-fast: false
    permissions:
      contents: read
      packages: write
    env:
      NEXT_PUBLIC_BOT_TOKEN: "${{ secrets.NEXT_PUBLIC_BOT_TOKEN }}"
      NEXT_PUBLIC_EMAIL: "${{ vars.NEXT_PUBLIC_EMAIL }}"
      NEXT_PUBLIC_URL: "${{ vars.NEXT_PUBLIC_URL }}"
      NEXT_PUBLIC_PHONE: "${{ vars.NEXT_PUBLIC_PHONE }}"
      NEXT_PUBLIC_MODE: "${{ inputs.environment }}"

      TG_CHANNEL_ID: "${{ inputs.environment }}_NEXT_PUBLIC_TG_CHANNEL_ID"
      COMPANY_URL: "${{ inputs.environment }}_NEXT_PUBLIC_COMPANY_URL"
      FREELANCER_URL: "${{ inputs.environment }}_NEXT_PUBLIC_FREELANCER_URL"
      BOT_URL: "${{ inputs.environment }}_NEXT_PUBLIC_BOT_URL"
      TRANSAK_API_KEY: "${{ inputs.environment }}_NEXT_PUBLIC_TRANSAK_API_KEY"

    steps:
      - name: Prepare image tag
        run: |
          #SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          #REF_NAME_SANITIZED=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/^-//')
          #if [[ -z "$REF_NAME_SANITIZED" || "$REF_NAME_SANITIZED" == "-" ]]; then
          #  REF_NAME_SANITIZED="default"
          #fi
          #echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          #echo "REF_NAME_SANITIZED=$REF_NAME_SANITIZED" >> $GITHUB_ENV
          #IMAGE_TAG="$REF_NAME_SANITIZED-$SHORT_SHA"
          #${{ github.run_number }}

          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/$REPO_NAME/${{ matrix.project }}:latest" >> $GITHUB_ENV
        shell: bash

      - name: Set envs for landing
        run: |
          echo "NEXT_PUBLIC_TG_CHANNEL_ID=${{ vars[env.TG_CHANNEL_ID] }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_COMPANY_URL=${{ vars[env.COMPANY_URL] }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FREELANCER_URL=${{ vars[env.FREELANCER_URL] }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BOT_URL=${{ vars[env.BOT_URL] }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_TRANSAK_API_KEY=${{ secrets[env.TRANSAK_API_KEY] }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Catch deps
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: Install dependencies
        if: ${{ github.event.inputs.deploy_landing == 'true' && matrix.project == 'landing' || github.event.inputs.deploy_company == 'true' && matrix.project == 'company' || github.event.inputs.deploy_freelancer == 'true' && matrix.project == 'freelancer' || github.event.inputs.deploy_admin == 'true' && matrix.project == 'admin' }}
        run: yarn install

      - name: Build NX project
        if: ${{ github.event.inputs.deploy_landing == 'true' && matrix.project == 'landing' || github.event.inputs.deploy_company == 'true' && matrix.project == 'company' || github.event.inputs.deploy_freelancer == 'true' && matrix.project == 'freelancer' || github.event.inputs.deploy_admin == 'true' && matrix.project == 'admin' }}
        run: npx nx build ${{ matrix.project }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image to GitHub Container Registry
        if: ${{ github.event.inputs.deploy_landing == 'true' && matrix.project == 'landing' || github.event.inputs.deploy_company == 'true' && matrix.project == 'company' || github.event.inputs.deploy_freelancer == 'true' && matrix.project == 'freelancer' || github.event.inputs.deploy_admin == 'true' && matrix.project == 'admin' }}
        run: |
          for i in {1..4}; do
            docker build -t ${{ env.IMAGE_NAME }} -f ./apps/${{ matrix.project }}/Dockerfile . && break || sleep 10;
          done
          for i in {1..4}; do
            docker push ${{ env.IMAGE_NAME }} && break || sleep 10;
          done

  deploy:
    needs: build-and-push
    if: ${{ needs.check-branch-and-env.outputs.error != 'true' }}
    runs-on: ubuntu-latest
    env:
      SSH_HOST_ENV: "${{ inputs.environment }}_SSH_HOST"
      SSH_USERNAME_ENV: "${{ inputs.environment }}_SSH_USERNAME"
      SSH_PRIVATE_KEY_ENV: "${{ inputs.environment }}_SSH_PRIVATE_KEY"
      SSH_PASSPHRASE_ENV: "${{ inputs.environment }}_SSH_PASSPHRASE"
    steps:
        #- name: Prepare image tag
        #run: |
        #SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        #REF_NAME_SANITIZED=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/^-//')
        #if [[ -z "$REF_NAME_SANITIZED" || "$REF_NAME_SANITIZED" == "-" ]]; then
        #REF_NAME_SANITIZED="default"
        #fi
        #echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
        #echo "REF_NAME_SANИТIZED=$REF_NAME_SANИТIZED" >> $GITHUB_ENV
        #IMAGE_TAG="$REF_NAME_SANITIZED-$SHORT_SHA"
        #
        #echo "IMAGE_NAME=${{ github.run_number }}:$IMAGE_TAG" >> $GITHUB_ENV
      - name: Setup environment variables
        run: |
          #echo "DEPLOY_PROJECTS=${{ github.event.inputs.projects }}" >> $GITHUB_ENV
          #echo "IMAGE_TAG=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
          echo "COMPANY=${{ github.event.inputs.deploy_company }}" >> $GITHUB_ENV
          echo "FREELANCER=${{ github.event.inputs.deploy_freelancer }}" >> $GITHUB_ENV
          echo "LANDING=${{ github.event.inputs.deploy_landing }}" >> $GITHUB_ENV
          echo "ADMIN=${{ github.event.inputs.deploy_admin }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets[env.SSH_HOST_ENV] }}
          username: ${{ secrets[env.SSH_USERNAME_ENV] }}
          key: ${{ secrets[env.SSH_PRIVATE_KEY_ENV] }}
          passphrase: ${{ secrets[env.SSH_PASSPHRASE_ENV] }}
#          source: "generate-docker-compose.sh"
          source: "compose.yaml"
          target: /mnt/freelbee/client

      - name: Set up SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets[env.SSH_HOST_ENV] }}
          username: ${{ secrets[env.SSH_USERNAME_ENV] }}
          key: ${{ secrets[env.SSH_PRIVATE_KEY_ENV] }}
          passphrase: ${{ secrets[env.SSH_PASSPHRASE_ENV] }}
          script: |
            echo "Deploying ${{ inputs.environment }} environment"
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd /mnt/freelbee/client

            REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            IMAGE_NAME="ghcr.io/$REPO_NAME"

            COMPANY_IMAGE="${IMAGE_NAME}/company:latest"
            FREELANCER_IMAGE="${IMAGE_NAME}/freelancer:latest"
            ADMIN_IMAGE="${IMAGE_NAME}/admin:latest"
            LANDING_IMAGE="${IMAGE_NAME}/landing:latest"

            export COMPANY_IMAGE
            export FREELANCER_IMAGE
            export ADMIN_IMAGE
            export LANDING_IMAGE

            docker-compose -f compose.yaml pull

            if [ "${{ env.COMPANY }}" == "true" ]; then
            docker-compose -f compose.yaml up -d company
            fi

            if [ "${{ env.FREELANCER }}" == "true" ]; then
            docker-compose -f compose.yaml up -d freelancer
            fi

            if [ "${{ env.LANDING }}" == "true" ]; then
            docker-compose -f compose.yaml up -d landing
            fi

            if [ "${{ env.ADMIN }}" == "true" ]; then
            docker-compose -f compose.yaml up -d admin
            fi


