name: Testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop
env:
  INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  pull-requests: read

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      admin-changed: ${{ steps.filter.outputs.admin }}
      company-changed: ${{ steps.filter.outputs.company }}
      freelancer-changed: ${{ steps.filter.outputs.freelancer }}
      landing-changed: ${{ steps.filter.outputs.landing }}

      packages-apps-changed: ${{ steps.filter.outputs.apps }}
      packages-pages-changed: ${{ steps.filter.outputs.pages }}
      packages-widgets-changed: ${{ steps.filter.outputs.widgets }}
      packages-features-changed: ${{ steps.filter.outputs.features }}
      packages-entities-changed: ${{ steps.filter.outputs.entities }}
      packages-shared-changed: ${{ steps.filter.outputs.shared }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter

        with:
          list-files: shell
          filters: |
            admin:
              - 'apps/admin/**'
            company:
              - 'apps/company/**'
            freelancer:
              - 'apps/freelancer/**'
            landing:
              - 'apps/landing/**'
            apps:
              - 'packages/a-app/**'
            pages:
              - 'packages/b-pages/**'
            widgets:
              - 'packages/c-widgets/**'
            features:
              - 'packages/d-features/**'
            entities:
              - 'packages/e-entities/**'
            shared:
              - 'packages/f-shared/**'

  tests-admin:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.admin-changed == 'true' }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      app_name: admin
      lint_command: yarn lint:admin
      test_command: yarn test:admin
      build_command: yarn build:admin

  tests-company:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.company-changed == 'true' }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      app_name: company
      lint_command: yarn lint:company
      test_command: yarn test:company
      build_command: yarn build:company

  tests-freelancer:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.freelancer-changed == 'true' }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      app_name: freelancer
      lint_command: yarn lint:freelancer
      test_command: yarn test:freelancer
      build_command: yarn build:freelancer

  tests-landing:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.landing-changed == 'true' }}
    run: |
      {
        echo '  NEXT_PUBLIC_BOT_TOKEN=${{ secrets.NEXT_PUBLIC_BOT_TOKEN }}'
        echo '  NEXT_PUBLIC_TG_CHANNEL_ID=${{ vars.TEST_NEXT_PUBLIC_TG_CHANNEL_ID }}'
        echo '  NEXT_PUBLIC_COMPANY_URL=${{ vars.TEST_NEXT_PUBLIC_COMPANY_URL }}'
        echo '  NEXT_PUBLIC_FREELANCER_URL=${{ vars.TEST_NEXT_PUBLIC_FREELANCER_URL }}'
      } >> apps/landing/.env
      cat apps/landing/.env
    uses: ./.github/workflows/reusable-tests.yml
    with:
      app_name: landing
      lint_command: yarn lint:landing
      test_command: yarn test:landing
      build_command: yarn build:landing

  tests-packages-app:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.packages-apps-changed == 'true' }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      app_name: app
      lint_command: yarn lint:app
      test_command: yarn test:app
      build_command: ''

  tests-packages-pages:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.packages-pages-changed == 'true' }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      app_name: pages
      lint_command: yarn lint:pages
      test_command: yarn test:pages
      build_command: ''

  tests-packages-widgets:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.packages-widgets-changed == 'true' }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      app_name: widgets
      lint_command: yarn lint:widgets
      test_command: yarn test:widgets
      build_command: ''

  tests-packages-features:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.packages-features-changed == 'true' }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      app_name: features
      lint_command: yarn lint:features
      test_command: yarn test:features
      build_command: ''

  tests-packages-entities:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.packages-entities-changed == 'true' }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      app_name: entities
      lint_command: yarn lint:entities
      test_command: yarn test:entities
      build_command: ''

  tests-packages-shared:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.packages-shared-changed == 'true' }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      app_name: shared
      lint_command: yarn lint:shared
      test_command: yarn test:shared
      build_command: ''